### ISSUE TITLE
Error in documentation of LoRa Container Format Description

### ISSUE THREAD

**Issue by digiteyezer** [allthingstalk/att-arduino-lorawan-client#1]
Order of the parameters mentioned in the TAB 'Examples Basic Data Packet' in the file "LoRa container format description.xlsx" for the Container 9 GPS is not correct.
First float value need to be 'Latitude', then comes the float value 'Longitude'.

Regards,
Filip

**Comment by esthoril** [comment]
Hi Filip,

You are correct. I removed the file entirely as the content is much more low-level info than someone using the library needs to know. For more info on containers, you can check our docs website (http://docs.allthingstalk.com/developers/data/default-payload-conversion/).

A reworked version of this SDK should become available in the upcoming weeks, which supports constructing your own custom binary payloads (so you can send data from multiple sensors in the same payload) on top of the default container format.
